CREATE TABLE product_details (
    PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255),
    PRODUCT_DESCRIPTION TEXT,
    PRODUCT_CATEGORY VARCHAR(255),
    PRODUCT_PRICE DECIMAL(10, 2),
    PRODUCT_QUANTITY INT
);


CREATE TABLE user_details (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(255),
    USER_FIRST_NAME VARCHAR(255),
    USER_LAST_NAME VARCHAR(255),
    USER_PASSWORD VARCHAR(255),
    USER_EMAIL VARCHAR(255),
    USER_ADDRESS TEXT
);


CREATE TABLE order_details (
    ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_CD VARCHAR(255) NOT NULL,
    ORDER_TIME TIMESTAMP,
    ADDRESS TEXT,
    ORDER_DATE DATE,
    PRODUCT_QUANTITY INT,
    PRODUCT_PRICE DECIMAL(10, 2),
    PRODUCT_ID INT REFERENCES product_details(PRODUCT_ID) ON DELETE CASCADE,
    USER_ID INT REFERENCES user_details(USER_ID) ON DELETE CASCADE
);