CREATE TABLE product_details (
    PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(23),
    PRODUCT_DESCRIPTION TEXT,
    PRODUCT_CATEGORY VARCHAR(23),
    PRODUCT_PRICE VARCHAR(10),
    PRODUCT_QUANTITY INT
);


CREATE TABLE user_details (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(23),
    USER_FIRST_NAME VARCHAR(23),
    USER_LAST_NAME VARCHAR(23),
    USER_PASSWORD VARCHAR(23),
    USER_EMAIL VARCHAR(23)
);

CREATE TABLE order_details (
    ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT REFERENCES user_details(USER_ID) ON DELETE CASCADE,
    ORDER_DATE VARCHAR(9)
);